spring.application.name=ProjetoSeguranca


springdoc.api-docs.enabled=true
springdoc.api-docs.path=/proj-seguranca/v3/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/proj-seguranca/swagger-ui.html

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/login_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123321ABC}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG
